"""`python -m biblecore build`, end to end, on a scratch copy of Joshua:
it must pass, leave every built fragment byte-identical (the build is a
no-op on a consistent book), and reproduce the committed occurrences.json.
Also checks canon leads against Joshua's committed sheets."""
import contextlib
import io
import os
import shutil

import support
from biblecore import build, leads

_tmp = None


def setup():
    global _tmp
    _tmp = support.scratch_book()


def teardown():
    shutil.rmtree(_tmp, ignore_errors=True)
    support.joshua_book()


def test_build_passes_and_changes_no_fragment():
    before = {n: support.read(os.path.join(_tmp, "units", n))
              for n in os.listdir(os.path.join(_tmp, "units"))}
    out = io.StringIO()
    with contextlib.redirect_stdout(out):
        rc = build.main([])
    fails = []
    if rc:
        fails.append(f"build failed (rc={rc}):\n{out.getvalue()[-1500:]}")
    for n, html in before.items():
        if support.read(os.path.join(_tmp, "units", n)) != html:
            fails.append(f"build changed {n}")
    committed = support.read(os.path.join(support.JOSHUA, "data", "occurrences.json"))
    if support.read(os.path.join(_tmp, "data", "occurrences.json")) != committed:
        fails.append("occurrences.json differs from Joshua's committed copy")
    if "build ok" not in out.getvalue():
        fails.append("no 'build ok' line")
    return fails


def test_canon_leads_match_joshuas_sheets():
    """Same leads as Joshua's canon_leads.py wrote, apart from the one
    header line naming the generator."""
    bible = leads.load_bible()
    freq = leads.verse_freq(bible)
    glosses = leads.load_glosses()
    fails = []
    for n in (1, 2, 3, 4):
        ours = support.read(leads.build(n, bible=bible, freq=freq, glosses=glosses))
        theirs = support.read(os.path.join(support.JOSHUA, "canon-leads",
                                           f"canon-leads-unit-{n:02d}.md"))
        strip = lambda t: [ln for ln in t.splitlines() if not ln.startswith("Generated by")]  # noqa: E731
        if strip(ours) != strip(theirs):
            fails.append(f"unit {n} leads differ from Joshua's sheet")
    return fails
