"""Generate a book's own colour well (data/palette.json).

    python tools/make_well.py ../Matthew --de 7
    python tools/make_well.py ../Mark --de 8 --out ../Mark/data/palette.json --dry

The starter well (template/data/palette.json) holds 65 colours and, at the
default spacing (CIEDE2000 10), only about 60 colours fit anywhere under the
readability limits, so a book that tracks ~80 threads or more (a Gospel) has
to lower the spacing and give the book a larger well. This builds one:

  - candidates: an sRGB grid, kept when the colour is readable as a word colour
    (Lab lightness 30-64, chroma 22-85) and has WCAG contrast of at least
    --min-contrast against the page background (read from the book's
    css/division.css `--bg`, or --bg);
  - the starter well's colours that pass, in their order, come first (a book
    keeps the family look the others have);
  - then farthest-point picks, each as far as possible from everything chosen,
    until no candidate is --de away from all of them.

So every pair in the well is at least --de apart and the order is the
preference order colour.assign_hues walks. Deterministic. Set the same
spacing in book.json (`"checks": {"colour_de_min": 7}`); `tools/recolour.py`
then re-assigns a shipped book's colours from the new well.
"""
import argparse
import json
import math
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
CORE = os.path.dirname(HERE)
sys.path.insert(0, CORE)

from biblecore.colour import _lab, ciede2000, contrast  # noqa: E402

L_RANGE = (30, 64)
C_RANGE = (22, 85)
DEFAULT_BG = "#f1ead9"


def page_bg(book_root):
    """The light theme's --bg from the book's division.css, else the default."""
    p = os.path.join(book_root, "css", "division.css")
    try:
        with open(p, encoding="utf-8") as fh:
            m = re.search(r"--bg:\s*(#[0-9a-fA-F]{6})", fh.read())
        return m.group(1).lower() if m else DEFAULT_BG
    except OSError:
        return DEFAULT_BG


def usable(h, bg, min_contrast):
    L, a, b = _lab(h)
    return (L_RANGE[0] <= L <= L_RANGE[1] and C_RANGE[0] <= math.hypot(a, b) <= C_RANGE[1]
            and contrast(h, bg) >= min_contrast)


def candidates(bg, min_contrast, step=8):
    out = []
    for r in range(0, 256, step):
        for g in range(0, 256, step):
            for b in range(0, 256, step):
                h = "#%02x%02x%02x" % (r, g, b)
                if usable(h, bg, min_contrast):
                    out.append(h)
    return out


def starter():
    with open(os.path.join(CORE, "template", "data", "palette.json"), encoding="utf-8") as fh:
        return json.load(fh)["well"]


def build_well(de, bg, min_contrast, step=8, seeds=None):
    """The well, in preference order (see the module docstring)."""
    cands = candidates(bg, min_contrast, step)
    chosen = []
    for h in (starter() if seeds is None else seeds):
        if usable(h, bg, min_contrast) and all(ciede2000(h, c) >= de for c in chosen):
            chosen.append(h)
    if not chosen:
        chosen.append(max(cands, key=lambda c: math.hypot(*_lab(c)[1:])))
    mind = {c: min(ciede2000(c, x) for x in chosen) for c in cands}
    while True:
        nxt = max(cands, key=lambda c: (mind[c], c))
        if mind[nxt] < de:
            break
        chosen.append(nxt)
        for c in cands:
            d = ciede2000(c, nxt)
            if d < mind[c]:
                mind[c] = d
    return chosen


def min_pairwise(well):
    return min((ciede2000(a, b) for i, a in enumerate(well) for b in well[i + 1:]),
               default=float("inf"))


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("book", nargs="?", default=".", help="the book's folder (default .)")
    ap.add_argument("--de", type=float, default=10, help="CIEDE2000 spacing (default 10)")
    ap.add_argument("--min-contrast", type=float, default=3.0,
                    help="WCAG contrast against the page background (default 3.0)")
    ap.add_argument("--bg", help="page background hex (default: the book's division.css --bg)")
    ap.add_argument("--step", type=int, default=8, help="sRGB grid step (default 8; smaller is slower)")
    ap.add_argument("--out", help="where to write (default <book>/data/palette.json)")
    ap.add_argument("--dry", action="store_true", help="report the size, write nothing")
    a = ap.parse_args(argv)

    bg = (a.bg or page_bg(a.book)).lower()
    well = build_well(a.de, bg, a.min_contrast, a.step)
    print(f"{len(well)} colours at CIEDE2000 >= {a.de:g}, contrast >= {a.min_contrast:g} on {bg}; "
          f"closest pair {min_pairwise(well):.1f}")
    if a.dry:
        return 0
    out = a.out or os.path.join(a.book, "data", "palette.json")
    note = (f"The colour well, in preference order. Generated by bible-core tools/make_well.py "
            f"(de {a.de:g}, contrast >= {a.min_contrast:g} on {bg}, grid step {a.step}); "
            f"do not hand-pick colours. Set checks.colour_de_min in book.json to the same spacing.")
    with open(out, "w", encoding="utf-8", newline="\n") as fh:
        json.dump({"_note": note, "well": well}, fh, indent=2, ensure_ascii=False)
        fh.write("\n")
    print("wrote", out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
